#!/bin/bash
#
# By Weisi Dai <weisi@x-research.com>

TEMPLATE='template.fsx'
PROBID=$1

set -C
sed "s/PROBID/$PROBID/g" $TEMPLATE > problem${PROBID}.fsx

set +C
(
cat <<EOF
FSHARPC=fsharpc --define:DEBUG

EOF
echo 'all: \'
for i in problem*.fsx; do
    echo -ne "\t"
    echo -n "$i" | sed 's/fsx/exe/'
    echo " \\"
done
echo
for i in problem*.fsx; do
    echo -n "$i" | sed 's/fsx/exe/'
    echo -n ': '
    echo "$i"
    echo -ne '\t'
    echo "\$(FSHARPC) algorithms.fs ${i}"
    echo
done
echo 'clean:'
echo -e '\trm problem*.exe problem*.res'
) > Makefile
exit
