#!/bin/bash
#
# By Weisi Dai <weisi@x-research.com>

TEMPLATE='template.fsx'
PROBID=$1

set -C
sed "s/PROBID/$PROBID/g" $TEMPLATE > problem${PROBID}.fsx

set +C
(
echo 'all: \'
for i in `seq 1 $PROBID`; do
    echo -ne "\t"
    echo "problem${i}.exe \\"
done
echo
for i in `seq 1 $PROBID`; do
    echo "problem${i}.exe: problem${i}.fsx"
    echo -ne '\t'
    echo "fsharpc problem${i}.fsx"
    echo
done
echo 'clean:'
echo -e '\trm problem*.exe'
) > Makefile
exit
